language: android
jdk: oraclejdk8
android:
  components:
  - tools
  - platform-tools
  - build-tools-27.0.1
  - android-27
  - extra-android-m2repository
  - sys-img-${ANDROID_ABI}-${ANDROID_TARGET}
script:
  - ./build-apk.sh
  